@startmindmap
* Utility
** Performance
*** Построение дэшбордов пользователей
**** Одновременная работа до 1000 пользователей на одном георграфическом кластере в период высокой нагрузки
*****_ M,M
**** Время построения дэшборда <1c
*****_ M,M
*** Получение данных из внешних источников
**** Обновление данных для дэшборда в течение 5 минут после получения данных
*****_ M,M
** Modifyability
*** Увеличение количества хранимых пользовательских данных в 4 раза в течение следующих 2х лет
****_ H,M
*** Расширение количества интегрированных вендорских систем из коробки
****_ H,H
*** Гибкость доработки пользовательского функционала 
****_ L,L
*** Гибкость и дешевизна в добавлении новых аналитик 
****_ M,M
** Availiability
*** Доступность данных дэшборда в оффлайн формате после построения
****_ H,H
*** Географически распределенная доступность
****_ H,H
** Secutity
*** Конфиденциальность персональных данных
****_ H,H


@endmindmap